apiVersion: v1
kind: Service
metadata:
  name: drhne53t43f
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "drhne53t43f"
    port: 8080
  selector:
    app: drhne53t43f
